### ISSUE TITLE
png in gitignore

### ISSUE THREAD

**Issue by Inni0401** [ChrisBaoCC/PSAP#1]
hello.

I would really like to use the PSAP for my project. I have noticed that the required png files are in the gitgnore. Would it be possible to add them to the repo?
Many thanks and best regards

**Comment by lucien-bao** [comment]
Hey there,

Since working on this project I've sinced switched computers and unfortunately don't have the images. I would recommend reaching out to my advisor for this project, Ramiro (https://github.com/rreareyes) to see if he can give you more info on this subject.
